<?php

declare(strict_types=1);

return [
    'paper' => [
        'title' => 'ZigBee Technology and Its Application in Wireless Home Automation Systems: A Survey',
        'authors' => [
            'Thoraya Obaid',
            'Haleemah Rashed',
            'Ali Abou-Elnour',
            'Muhammad Rehan',
            'Mussab Muhammad Saleh',
            'Mohammed Tarique',
        ],
        'year' => 2014,
        'journal' => 'International Journal of Computer Networks & Communications',
        'journal_short' => 'IJCNC',
        'volume' => '6',
        'issue' => '4',
        'pages' => '115-131',
        'doi' => '10.5121/ijcnc.2014.6411',
        'doi_url' => 'https://doi.org/10.5121/ijcnc.2014.6411',
        'pdf_url' => 'https://airccse.org/journal/cnc/6414cnc11.pdf',
        'index_url' => 'https://airccj.org/csecfp/library/Search.php?title=igBee+Technology+and+its+application+in+Wireless+Home+Automation+systems%3A+a+survey&x=43&y=13',
        'keywords' => [
            'Home automation',
            'ZigBee',
            'Z-Wave',
            'Insteon',
            'Wavenis',
            'PAN',
            'Voice control',
            'Energy management',
            'Assistive homes',
            'Industrial automation',
        ],
        'citation' => 'Obaid, T., Rashed, H., Abou-Elnour, A., Rehan, M., Muhammad Saleh, M., & Tarique, M. (2014). ZigBee Technology and Its Application in Wireless Home Automation Systems: A Survey. International Journal of Computer Networks & Communications, 6(4), 115-131. https://doi.org/10.5121/ijcnc.2014.6411',
        'summary' => 'The paper surveys ZigBee-based wireless home automation systems, compares ZigBee with Z-Wave, Insteon, Wavenis, Bluetooth, and WiFi, and identifies major application classes and design challenges for practical WHAS deployments.',
    ],
    'zigbee_features' => [
        'data_rates' => ['250 kb/s', '40 kb/s', '20 kb/s'],
        'topologies' => ['Star', 'Tree', 'Mesh', 'Peer-to-peer'],
        'addressing' => ['16-bit short address', '64-bit extended address'],
        'access_method' => 'Carrier Sense Multiple Access with Collision Avoidance',
        'frequency_bands' => ['868 MHz', '915 MHz', '2.4 GHz'],
        'range' => '10-100 meters depending on topology, power, and environment',
        'network_size' => 'Up to 64,000 nodes in the paper summary',
        'device_types' => [
            'Coordinator' => 'Forms the network and bridges other networks.',
            'Router' => 'Extends coverage and relays traffic for child devices.',
            'End device' => 'Performs sensing or actuation and can sleep to conserve power.',
            'Full Function Device' => 'Can route, coordinate, and support richer processing needs.',
            'Reduced Function Device' => 'Focused low-power device with limited communication roles.',
        ],
    ],
    'technologies' => [
        [
            'id' => 'zigbee',
            'name' => 'ZigBee',
            'frequency' => '868 MHz, 915 MHz, 2.4 GHz',
            'range_meters' => 100,
            'network_size' => 64000,
            'power_profile' => 'Very low',
            'installation_profile' => 'Low-power sensor and actuator networks with mesh expansion.',
            'strengths' => ['Low power', 'Large network scale', 'Mesh support', 'Strong fit for sensors'],
            'tradeoffs' => ['Gateway needed for internet connectivity', 'ISM-band interference', 'Careful address and routing planning required'],
            'score_bias' => 18,
        ],
        [
            'id' => 'zwave',
            'name' => 'Z-Wave',
            'frequency' => '868 MHz, 908 MHz, 2.4 GHz',
            'range_meters' => 100,
            'network_size' => 232,
            'power_profile' => 'Low',
            'installation_profile' => 'Residential and light commercial short-message control.',
            'strengths' => ['Mature home automation ecosystem', 'Good residential fit', 'Low power'],
            'tradeoffs' => ['Smaller network size than ZigBee', 'Vendor ecosystem dependency'],
            'score_bias' => 5,
        ],
        [
            'id' => 'insteon',
            'name' => 'Insteon',
            'frequency' => '904 MHz',
            'range_meters' => 45,
            'network_size' => 256,
            'power_profile' => 'Not specified',
            'installation_profile' => 'Hybrid RF and powerline home automation.',
            'strengths' => ['RF and powerline options', 'Mesh-style communication'],
            'tradeoffs' => ['Limited hop depth', 'Technology-specific ecosystem'],
            'score_bias' => 2,
        ],
        [
            'id' => 'wavenis',
            'name' => 'Wavenis',
            'frequency' => '433 MHz, 868 MHz, 915 MHz',
            'range_meters' => 1000,
            'network_size' => 0,
            'power_profile' => 'Ultra-low',
            'installation_profile' => 'Longer-range low-power monitoring and control.',
            'strengths' => ['Long range', 'Ultra-low power'],
            'tradeoffs' => ['Less common WHAS ecosystem', 'Unknown practical network scale in the paper comparison'],
            'score_bias' => 4,
        ],
        [
            'id' => 'bluetooth',
            'name' => 'Bluetooth',
            'frequency' => '2.4 GHz',
            'range_meters' => 10,
            'network_size' => 8,
            'power_profile' => 'Medium',
            'installation_profile' => 'Short-range personal area connectivity.',
            'strengths' => ['Common device support', 'Simple short-range links'],
            'tradeoffs' => ['Small network size', 'Range limitation', 'Higher power than ZigBee for WHAS use cases'],
            'score_bias' => -8,
        ],
        [
            'id' => 'wifi',
            'name' => 'WiFi',
            'frequency' => '2.4 GHz, 5 GHz',
            'range_meters' => 100,
            'network_size' => 2007,
            'power_profile' => 'High',
            'installation_profile' => 'IP connectivity and high-throughput local networks.',
            'strengths' => ['Native IP access', 'Broad ecosystem', 'Higher throughput'],
            'tradeoffs' => ['High power consumption', 'Interference with 2.4 GHz sensors', 'Less ideal for battery sensor nodes'],
            'score_bias' => -2,
        ],
    ],
    'applications' => [
        [
            'id' => 'security',
            'name' => 'Security and Safety Monitoring',
            'paper_signal' => 'The survey covers ZigBee systems for door/window monitoring, smoke, gas leak, water flooding, and remote warning.',
            'design_focus' => 'High availability, low-latency alarms, tamper evidence, and reliable gateway notification.',
            'key_devices' => ['Door sensor', 'Smoke sensor', 'Gas sensor', 'Water leak sensor', 'Alarm actuator'],
        ],
        [
            'id' => 'surveillance',
            'name' => 'Smart Surveillance and Remote Monitoring',
            'paper_signal' => 'The survey discusses ZigBee gateways, remote monitoring, location systems, and abnormal-image or warning-message workflows.',
            'design_focus' => 'Gateway availability, remote access controls, sensor placement, and clear event escalation.',
            'key_devices' => ['Gateway', 'Presence sensor', 'Location beacon', 'Camera trigger', 'Notification service'],
        ],
        [
            'id' => 'energy',
            'name' => 'Energy Management',
            'paper_signal' => 'The survey includes power monitoring, load control, current measurement, overload response, and energy-aware deployment.',
            'design_focus' => 'Load visibility, appliance control, safe circuit response, and long battery life.',
            'key_devices' => ['Smart outlet', 'Current sensor', 'Relay', 'Power meter', 'Load controller'],
        ],
        [
            'id' => 'assistive',
            'name' => 'Assistive Home and Voice Control',
            'paper_signal' => 'The survey covers voice-controlled ZigBee systems designed to support elderly people and people with disabilities.',
            'design_focus' => 'Accessible interfaces, fallback controls, response confirmation, and resilient local operation.',
            'key_devices' => ['Voice interface', 'Touch panel', 'Relay module', 'Accessible notification', 'Profile manager'],
        ],
    ],
    'challenges' => [
        [
            'id' => 'resource-constraint',
            'name' => 'Resource-constrained nodes',
            'severity' => 'High',
            'paper_signal' => 'Sensors and nodes used in WHAS have limited processing power, memory, and battery.',
            'mitigation' => 'Use FFD devices for routing and processing-heavy roles, reserve RFD devices for low-power sensing, and keep payloads compact.',
            'controls' => ['device-role-planning', 'battery-budgeting', 'payload-minimization'],
        ],
        [
            'id' => 'limited-range',
            'name' => 'Limited transmission range',
            'severity' => 'High',
            'paper_signal' => 'ZigBee range can require multihop communication and router placement to cover a deployment.',
            'mitigation' => 'Plan routers, mesh routes, signal margins, and installation zones before deployment.',
            'controls' => ['topology-planning', 'router-density', 'site-survey'],
        ],
        [
            'id' => 'standard-dependency',
            'name' => 'IEEE 802.15.4 dependency',
            'severity' => 'Medium',
            'paper_signal' => 'ZigBee depends on the physical and MAC layers of IEEE 802.15.4.',
            'mitigation' => 'Track standard changes, chipset support, firmware maturity, and compatibility across devices.',
            'controls' => ['standards-tracking', 'device-certification', 'firmware-lifecycle'],
        ],
        [
            'id' => 'ism-interference',
            'name' => 'ISM-band interference',
            'severity' => 'High',
            'paper_signal' => 'ZigBee WHAS must coexist with Bluetooth, WiFi, cordless phones, microwave ovens, and other devices in shared bands.',
            'mitigation' => 'Perform channel planning, interference scans, gateway placement, and coexistence testing.',
            'controls' => ['channel-planning', 'coexistence-testing', 'gateway-placement'],
        ],
        [
            'id' => 'internet-connectivity',
            'name' => 'Internet connectivity requirement',
            'severity' => 'Medium',
            'paper_signal' => 'Remote monitoring may require internet connectivity through a suitable gateway.',
            'mitigation' => 'Use a hardened gateway, authenticated remote access, encrypted communication, and fail-safe local operation.',
            'controls' => ['gateway-hardening', 'remote-access-control', 'local-fail-safe'],
        ],
        [
            'id' => 'orphan-nodes',
            'name' => 'Orphan node and address planning',
            'severity' => 'Medium',
            'paper_signal' => 'The paper notes orphan-node risk when devices cannot obtain suitable network addresses.',
            'mitigation' => 'Plan network depth, child limits, address allocation, and parent-device capacity.',
            'controls' => ['address-planning', 'parent-capacity', 'join-monitoring'],
        ],
        [
            'id' => 'security-exposure',
            'name' => 'Wireless security exposure',
            'severity' => 'High',
            'paper_signal' => 'ZigBee networks can be exposed to wireless mesh protocol attacks and penetration risk.',
            'mitigation' => 'Apply key management, secure commissioning, gateway isolation, event logging, and tamper-aware deployment.',
            'controls' => ['secure-commissioning', 'key-management', 'security-monitoring'],
        ],
        [
            'id' => 'retrofit-cost',
            'name' => 'Retrofit and installation cost',
            'severity' => 'Medium',
            'paper_signal' => 'The paper identifies installation and retrofit cost as a practical barrier for existing homes.',
            'mitigation' => 'Use phased deployment, reusable gateway patterns, minimal wiring changes, and clear maintenance runbooks.',
            'controls' => ['phased-rollout', 'maintenance-runbook', 'cost-modeling'],
        ],
    ],
    'controls' => [
        ['id' => 'device-role-planning', 'name' => 'Plan coordinator, router, FFD, RFD, and end-device roles', 'category' => 'Network design', 'weight' => 9],
        ['id' => 'battery-budgeting', 'name' => 'Define battery-life budgets for each sensor class', 'category' => 'Power management', 'weight' => 8],
        ['id' => 'payload-minimization', 'name' => 'Keep sensor payloads compact and event-driven', 'category' => 'Protocol efficiency', 'weight' => 5],
        ['id' => 'topology-planning', 'name' => 'Select star, tree, or mesh topology by home size and risk', 'category' => 'Network design', 'weight' => 9],
        ['id' => 'router-density', 'name' => 'Place routers to support reliable multihop coverage', 'category' => 'Coverage', 'weight' => 8],
        ['id' => 'site-survey', 'name' => 'Perform signal and placement survey before installation', 'category' => 'Coverage', 'weight' => 7],
        ['id' => 'standards-tracking', 'name' => 'Track IEEE 802.15.4 and ZigBee stack compatibility', 'category' => 'Lifecycle', 'weight' => 5],
        ['id' => 'device-certification', 'name' => 'Use certified or validated devices where possible', 'category' => 'Lifecycle', 'weight' => 6],
        ['id' => 'firmware-lifecycle', 'name' => 'Maintain firmware inventory and update cadence', 'category' => 'Lifecycle', 'weight' => 7],
        ['id' => 'channel-planning', 'name' => 'Plan channels around WiFi and other 2.4 GHz interference', 'category' => 'Coexistence', 'weight' => 8],
        ['id' => 'coexistence-testing', 'name' => 'Test coexistence with WiFi, Bluetooth, and household appliances', 'category' => 'Coexistence', 'weight' => 8],
        ['id' => 'gateway-placement', 'name' => 'Place gateways for stable bridging and usable signal margins', 'category' => 'Gateway', 'weight' => 7],
        ['id' => 'gateway-hardening', 'name' => 'Harden the home automation gateway', 'category' => 'Gateway', 'weight' => 9],
        ['id' => 'remote-access-control', 'name' => 'Protect remote access with strong authentication and encryption', 'category' => 'Security', 'weight' => 9],
        ['id' => 'local-fail-safe', 'name' => 'Keep safety functions operational without internet access', 'category' => 'Resilience', 'weight' => 8],
        ['id' => 'address-planning', 'name' => 'Plan network addressing, depth, and child limits', 'category' => 'Network design', 'weight' => 7],
        ['id' => 'parent-capacity', 'name' => 'Validate parent-device capacity before joining nodes', 'category' => 'Network design', 'weight' => 6],
        ['id' => 'join-monitoring', 'name' => 'Monitor join failures and orphan-node indicators', 'category' => 'Operations', 'weight' => 6],
        ['id' => 'secure-commissioning', 'name' => 'Use secure commissioning for new devices', 'category' => 'Security', 'weight' => 9],
        ['id' => 'key-management', 'name' => 'Manage network keys and device trust deliberately', 'category' => 'Security', 'weight' => 9],
        ['id' => 'security-monitoring', 'name' => 'Monitor for unusual traffic, device joins, and gateway events', 'category' => 'Security', 'weight' => 8],
        ['id' => 'phased-rollout', 'name' => 'Deploy in phases to reduce retrofit risk', 'category' => 'Delivery', 'weight' => 5],
        ['id' => 'maintenance-runbook', 'name' => 'Maintain installation and support runbooks', 'category' => 'Operations', 'weight' => 5],
        ['id' => 'cost-modeling', 'name' => 'Model installation, maintenance, and expansion cost', 'category' => 'Delivery', 'weight' => 5],
    ],
];

